name: fom_module
services:
  fom_module:
    container_name: fom_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    command: python -m fom_rest_node --port 3019 --fom_url ${fom_URL}
    env_file: .env
    volumes:
      - ./src:/home/app/fom_module/src
      - ./tests:/home/app/fom_module/tests
    ports:
      - 3019:3019